<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708204249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : User, Category, Vehicle, Tip, TipRevision, CommitteeVote, Tag, UsefulVote, Report.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, pseudo VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, score INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_pseudo ON app_user (pseudo)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C1727ACA70 ON category (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_category_slug ON category (slug)');
        $this->addSql('CREATE TABLE committee_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, decision VARCHAR(10) NOT NULL, comment TEXT DEFAULT NULL, voted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revision_id INT NOT NULL, member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD3EB7471DFA7C8F ON committee_vote (revision_id)');
        $this->addSql('CREATE INDEX IDX_CD3EB7477597D3FE ON committee_vote (member_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_vote_revision_member ON committee_vote (revision_id, member_id)');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tip_id INT NOT NULL, reporter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784476C47F6 ON report (tip_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_slug ON tag (slug)');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, published_title VARCHAR(200) DEFAULT NULL, published_content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT NOT NULL, category_id INT NOT NULL, vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4883B84CF675F31B ON tip (author_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C12469DE2 ON tip (category_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C545317D1 ON tip (vehicle_id)');
        $this->addSql('CREATE TABLE tip_tag (tip_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (tip_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_3CC4E47E476C47F6 ON tip_tag (tip_id)');
        $this->addSql('CREATE INDEX IDX_3CC4E47EBAD26311 ON tip_tag (tag_id)');
        $this->addSql('CREATE TABLE tip_revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24E315C3476C47F6 ON tip_revision (tip_id)');
        $this->addSql('CREATE TABLE useful_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, useful BOOLEAN NOT NULL, voted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tip_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F98D2EDE476C47F6 ON useful_vote (tip_id)');
        $this->addSql('CREATE INDEX IDX_F98D2EDEA76ED395 ON useful_vote (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_useful_vote_tip_user ON useful_vote (tip_id, user_id)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, make VARCHAR(100) NOT NULL, model VARCHAR(100) NOT NULL, engine VARCHAR(150) DEFAULT NULL, label VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, proposed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B80E486DAB5A938 ON vehicle (proposed_by_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE committee_vote ADD CONSTRAINT FK_CD3EB7471DFA7C8F FOREIGN KEY (revision_id) REFERENCES tip_revision (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE committee_vote ADD CONSTRAINT FK_CD3EB7477597D3FE FOREIGN KEY (member_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CF675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip_tag ADD CONSTRAINT FK_3CC4E47E476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tip_tag ADD CONSTRAINT FK_3CC4E47EBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tip_revision ADD CONSTRAINT FK_24E315C3476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE useful_vote ADD CONSTRAINT FK_F98D2EDE476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE useful_vote ADD CONSTRAINT FK_F98D2EDEA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486DAB5A938 FOREIGN KEY (proposed_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE committee_vote DROP CONSTRAINT FK_CD3EB7471DFA7C8F');
        $this->addSql('ALTER TABLE committee_vote DROP CONSTRAINT FK_CD3EB7477597D3FE');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784476C47F6');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CF675F31B');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C12469DE2');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C545317D1');
        $this->addSql('ALTER TABLE tip_tag DROP CONSTRAINT FK_3CC4E47E476C47F6');
        $this->addSql('ALTER TABLE tip_tag DROP CONSTRAINT FK_3CC4E47EBAD26311');
        $this->addSql('ALTER TABLE tip_revision DROP CONSTRAINT FK_24E315C3476C47F6');
        $this->addSql('ALTER TABLE useful_vote DROP CONSTRAINT FK_F98D2EDE476C47F6');
        $this->addSql('ALTER TABLE useful_vote DROP CONSTRAINT FK_F98D2EDEA76ED395');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E486DAB5A938');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE committee_vote');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE tip_tag');
        $this->addSql('DROP TABLE tip_revision');
        $this->addSql('DROP TABLE useful_vote');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
